# STG file generated by Workcraft -- http://workcraft.org
.internal csc1
.inputs Ai Ri
.outputs Ao Ro
.graph
Ai+ csc1+
Ai- Ro+
Ao+ Ri-
Ao- Ri+
Ri+ Ao+ Ro+
Ri- csc1-
Ro+ Ai+ Ao+
Ro- Ai- csc1-
csc1+ Ro-
csc1- Ao-
.marking {<Ai-,Ro+> <Ao-,Ri+>}
.end
