# STG file generated by Workcraft -- http://workcraft.org
.inputs Ai Ri
.outputs Ao Ro
.graph
Ai+ Ro-
Ai- p1
Ao+ Ri-
Ao- Ai- p0
Ri+ Ao+ Ro+
Ri- Ao-
Ro+ Ai+ Ao+
Ro- Ao-
p0 Ri+
p1 Ro+
.marking {p0 p1}
.end
