# STG file generated by Workcraft -- http://workcraft.org
.inputs Ai Ri
.outputs Ao Ro
.graph
Ai+ Ro-
Ai- p1
Ao+ Ri- Ro-
Ao- p0
Ri+ Ro+
Ri- Ao-
Ro+ Ai+ Ao+
Ro- Ai- Ao-
p0 Ri+
p1 Ro+
.marking {p0 p1}
.end
