# STG file generated by Workcraft -- http://workcraft.org
.inputs DSr DSw LDTACK
.outputs D DTACK LDS
.graph
D+ LDS+
D+/1 DTACK+/1
D- DTACK+
D-/1 Merge1 Merge2
DSr+ LDS+/1
DSr- D-/1
DSw+ D+
DSw- Merge1 Merge2
DTACK+ DSw-
DTACK+/1 DSr-
DTACK- Choice1
LDS+ LDTACK+
LDS+/1 LDTACK+/1
LDS- LDTACK-
LDTACK+ D-
LDTACK+/1 D+/1
LDTACK- Choice2
Choice1 DSr+ DSw+
Choice2 D+ LDS+/1
Merge1 DTACK-
Merge2 LDS-
.marking {Choice1 Choice2}
.end
